services:
  traefik:
    image: traefik:2.8
    container_name: traefik
    restart: always
    networks:
      - zap-network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.yml:/traefik.yml:ro"
      - "./acme.json:/acme.json"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=zap-network"
      - "traefik.port=80"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"

  backend:
    build: .
    container_name: backend-container
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://novus:Juan2010@postgres:5432/vurnerDB
      - NODE_ENV=development
    depends_on:
      postgres:
        condition: service_healthy
      zap:
        condition: service_started
    networks:
      - zap-network
    command: |
      sh -c "npm install && npx prisma generate && npm start"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=zap-network"
      - "traefik.port=80"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.rule=Host(`security.bluetech.software`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.backend.loadbalancer.server.port=3000"

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=novus
      - POSTGRES_PASSWORD=Juan2010
      - POSTGRES_DB=vurnerDB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - zap-network
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U novus -d vurnerDB
      interval: 5s
      timeout: 5s
      retries: 5

  zap:
    image: zaproxy/zap-stable
    user: zap
    ports:
      - 8080:8080
    command: zap.sh -daemon -host 0.0.0.0 -port 8080 -config api.addrs.addr.name=.*
      -config api.addrs.addr.regex=true -config api.disablekey=true
    networks:
      - zap-network

networks:
  zap-network:
    external: true

volumes:
  postgres_data: null
