entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

api:
  dashboard: true
  insecure: true
  entryPoint: websecure  # API dashboard should use a defined entryPoint

providers:
  docker:
    exposedByDefault: false
    network: zap-network

certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@bluetech.software
      storage: acme.json
      httpChallenge:
        entryPoint: web  # Use the "web" entrypoint for the HTTP challenge

log:
  level: INFO

http:
  routers:
    redirect-to-https:
      entryPoints:
        - web  # Redirect router for HTTP traffic
      rule: "HostRegexp(`{any:.*}`)"
      service: noop@internal
      middlewares:
        - redirect-to-https

  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true
