entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt
        domains:
          - main: "bluetech.software"
            sans:
              - "*.bluetech.software"

api:
  dashboard: true
  insecure: true

providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@bluetech.software
      storage: acme.json
      httpChallenge:
        entryPoint: web
      tlsChallenge: {}

log:
  level: INFO
