entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false
    network: zap-network

certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@bluetech.software
      storage: acme.json
      httpChallenge:
        entryPoint: web

log:
  level: INFO
